### PR TITLE
Switch to GitHub Actions CI.

### LINKED ISSUE #42: GitHub Actions CI
@vladikoff can you register the org on GitHub Actions CI?

Then I could make the switch and we drop Travis and AppVeyor from all the repos.

### PR DESCRIPTION
**Pull request by XhmikosR**
Notes:

1. I had to use 8.16.1 which is the latest Node.js 8.x version at the time of writing, due to https://github.com/actions/setup-node/issues/27
2. I'm not sure if we can link to master branch's actions only
3. I kept the PowerShell test, but I'm not sure if it's 100% right

Fixes #42 

/CC @vladikoff for thoughts

### CODE REVIEW

**Comment by vladikoff** [comment]
This looks exciting!!

**Comment by XhmikosR** [comment]
So, how do you want to proceed with this?

We should probably make this another major version bump and in the projects we update to the new version we'd need to remove Travis CI and AppVeyor from hooks and/or integrations.

**Comment by XhmikosR** [comment]
Maybe wait until https://github.com/actions/setup-node/issues/27 is fixed?

**Comment by vladikoff** [comment]
@XhmikosR do we still need an upstream fix for node 8?

**Comment by XhmikosR** [comment]
Not sure, I'll try again tomorrow.

**Comment by XhmikosR** [comment]
@vladikoff PR updated. I didn't add caching because I'd rather err on the safe side. Do note that if we merge this it should be a major version bump.

**Pull request merged**
