### PR TITLE
Update Node.js versions CI are using.

### PR DESCRIPTION
**Pull request by XhmikosR**
Remove 0.10, 0.12 and 5, and add 7.

/CC @vladikoff @shama: Do **NOT** merge yet.

We should discuss how we are going to proceed. My suggestion is to support LTS releases and the latest one, which is what I did in this PR.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Ping @vladikoff

**Comment by vladikoff** [comment]
👍

**Comment by XhmikosR** [comment]
So @vladikoff does this mean that we should change the minimum supported version of contrib plugins to 4?

**Comment by vladikoff** [comment]
@XhmikosR IMHO we don't have to change anything unless we cannot support node 0.10 in that plugin for whatever reason

**Comment by XhmikosR** [comment]
Well, then you shouldn't have merged this PR. I mean, we should only test what we support. And if we don't test, then it doesn't make sense to support it.

**Comment by XhmikosR** [comment]
Should I just add node.js 0.10 back then if you want to keep support for 0.10? Please note that 0.10 is ancient though.

**Comment by vladikoff** [comment]
@XhmikosR it's fine to drop 0.10 in internal, only we use it

**Comment by XhmikosR** [comment]
But this repo applies changes to all contrib plugins when updated. We better be consistent.

**Comment by vladikoff** [comment]
Oh right it copies its own travis.yml. Sure that's fine, we can propagate the change when we want then.

**Pull request merged**
