### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by XhmikosR**
**DO NOT MERGE**

@vladikoff: please review this. I'm not sure if we should even test x86 anymore... Also, do we have an official ESLint config? We should switch to ESLint and ES6.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oh, and another alternative would be to drop AppVeyor in favor of Travis for Windows too. But I think it's too soon because Windows on Travis is in its early stage.

**Comment by XhmikosR** [comment]
@vladikoff: can I get a reply here? Remember, do not merge blindly!

**Comment by vladikoff** [comment]
@XhmikosR looks good to me! And I agree, let's stay with AppVeyor for now

**Comment by XhmikosR** [comment]
@vladikoff: how about an ESLint config? Is there one we can use in all plugins?

**Comment by vladikoff** [comment]
> how about an ESLint config?

We always used JSHint for everything, so we don't have one

**Comment by XhmikosR** [comment]
I see ESLint being used in grunt itself https://github.com/gruntjs/grunt/blob/master/.eslintrc.

Who maintains this config? We should just make one and use it everywhere.

**Comment by vladikoff** [comment]
@XhmikosR  eslint-config-grunt  is at https://www.npmjs.com/package/eslint-config-grunt, we can fork it if you want

**Comment by XhmikosR** [comment]
We should move that under the org and adapt it. Are you in touch with @markelog maybe?

**Comment by vladikoff** [comment]
> We should move that under the org and adapt it

That works too!

**Comment by vladikoff** [comment]
This could be independent of this PR also

**Comment by XhmikosR** [comment]
I'll update this PR and merge it and when we have a working ESLint config, I'm gonna start migrating the plugins.

**Comment by markelog** [comment]
Okay, invited @vladikoff to npm (couldn't find @XhmikosR name there) and sent invite. So now you have the ability to transfer the repo I hope, since I can't do it cause I don't have the writing rights to gruntjs org, obviously haha

**Comment by XhmikosR** [comment]
On npm it's `xhmikosr`

**Pull request merged**
