### PR TITLE
Update JSHint config.

### PR DESCRIPTION
**Pull request by XhmikosR**
Remove eqnull and sub.

### CODE REVIEW

**Comment by shama** [comment]
Why are we removing these two?

**Comment by XhmikosR** [comment]
`eqnull` because I'd rather be explicit. `sub` we don't seem to use it anywhere as far as I can tell.

**Comment by shama** [comment]
I think `eqnull` is used frequently and we don't want to get warnings about using `if (foo == null)`.

**Comment by XhmikosR** [comment]
@shama: the only cases I found us using non strict comparison for `null` is 3 instances in grunt-contrib-coffee.

**Comment by shama** [comment]
@XhmikosR It's used a bit in grunt core and I believe is the preference of the original code style created by @cowboy so I don't think we should remove it.

**Comment by XhmikosR** [comment]
But this plugin isn't included in core, is it?

**Comment by shama** [comment]
@XhmikosR I don't want to use multiple code styles in the Grunt org. Removing `sub` is fine as it's deprecated but I don't see any reason why we need to remove `eqnull`.

**Comment by XhmikosR** [comment]
Well, in my opinion, `eqnull` is just useless. Don't we know what is
returned? If not, shouldn't we know?

We already use strict comparison for everything else.

**Comment by shama** [comment]
I disagree. `eqnull` is useful because `undefined` exists. We would need to change `if (foo == null)` to `if (foo === null || foo === undefined)`. Changing it now and explicitly writing that is a waste of time. Unless a specific issue arises, I'd rather not worry and just use the existing code style.

**Pull request closed without merging**
